package com.unal.crocante;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Martinez
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    MysqlConexion conexion = new MysqlConexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_Usuario = new javax.swing.JTextField();
        jButton_Aceptar = new javax.swing.JButton();
        textoContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ver = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setMaximumSize(new java.awt.Dimension(230, 260));
        setMinimumSize(new java.awt.Dimension(230, 260));
        setPreferredSize(new java.awt.Dimension(330, 230));
        setSize(new java.awt.Dimension(230, 260));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Usuario.setToolTipText("");
        Texto_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Texto_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jButton_Aceptar.setText("Ingresar");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, -1));
        getContentPane().add(textoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 30));

        jLabel1.setForeground(new java.awt.Color(240, 109, 19));
        jLabel1.setText("CONTRASEÑA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setForeground(new java.awt.Color(240, 109, 19));
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerMouseClicked(evt);
            }
        });
        getContentPane().add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(240, 109, 19));
        jPanel1.setForeground(new java.awt.Color(0, 99, 154));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 110, 220));

        jLabel3.setForeground(new java.awt.Color(240, 109, 19));
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setForeground(new java.awt.Color(240, 109, 19));
        jLabel4.setText("USUARIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Texto_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto_UsuarioActionPerformed

    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed

// Se llaman todos los string necdesarios de los cuadros de texto
        String usuario = Texto_Usuario.getText();
        String contrasena = String.valueOf(textoContrasena.getPassword());

// Se envia al objeto conexion el usuario y la contrasena
        conexion.setPassword(contrasena);
        conexion.setUser(usuario);

// Se llama la funcion iniciarConexion() y se crea la variable conectar que va a servir para todo lo de mysql
        Connection conectar = conexion.iniciarConexion();

// Se comprueba si la conexion fue exitosa
        if (conectar != null) {
            try {
// Preparamos la consulta para buscar el cargo de la persona y que pueda acceder a su vista correspondiente

                String consulta = "select Mostrar_Cargo('" + usuario + "')";
                String NombreC =  "Call Mostrar_Nombre('" + usuario + "');";
                
                PreparedStatement a = conectar.prepareStatement(consulta);
                ResultSet resultado = a.executeQuery();
                resultado.next();
                
                PreparedStatement b = conectar.prepareStatement(NombreC);
                ResultSet resultado2 = b.executeQuery();
                resultado2.next();
                
                               
                String cargo = resultado.getString(1);
                String Apellido = resultado2.getString(2);
                
                if (GERENTE.equals(cargo)) {

                    JOptionPane.showMessageDialog(null, "Bienvenido Gerente : " + usuario + " " +""+ Apellido);
                    new Menu().setVisible(true);
                    dispose();

                } else if (CAJERO.equals(cargo)) {

                    JOptionPane.showMessageDialog(null, "Bienvenido Cajero : " + usuario + " " + Apellido);

                } else {

                    JOptionPane.showMessageDialog(null, "Su cargo no tiene permitido entrar a la base de datos");

                }

                System.out.println(cargo);

// Recorremos el resultado, mientras haya registros para leer, y escribimos el resultado en pantalla.
            } catch (SQLException sqle) {
                System.out.println("Imposible realizar consulta ... FAIL");
                sqle.printStackTrace();
            }

        } else {

            JOptionPane.showMessageDialog(null, "No se ha podido conectar correctamente a la base de datos\nVuelva a ingresar su ingresario y contraseña");

        }

// Recorremos el resultado, mientras haya registros para leer, y escribimos el resultado en pantalla.
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseClicked
     if (Ver.isSelected()) {
      textoContrasena.setEchoChar((char)0); //password = JPasswordField
   } else {
      textoContrasena.setEchoChar('*');
   }   // TODO add your handling code here:
    }//GEN-LAST:event_VerMouseClicked
    private static final String CAJERO = "Cajero";
    private static final String GERENTE = "Gerente";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Texto_Usuario;
    private javax.swing.JCheckBox Ver;
    public javax.swing.JButton jButton_Aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField textoContrasena;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton crearBoton() {

        ImageIcon imageIcon = new ImageIcon("src\\main\\resources\\accessKey.jpeg");
        return new javax.swing.JButton(imageIcon);

    }
}
